### ISSUE TITLE
Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by oprypkhantc** [AnourValar/eloquent-serialize#11]
Hey.

We're running PHP 8.1.5 and Laravel 9.10.0 and getting this deprecation:
```log
[2022-04-30 14:28:41] pipeline.WARNING: ErrorException: Automatic conversion of false to array is deprecated in /app/vendor/anourvalar/eloquent-serialize/src/Grammars/EloquentBuilderGrammar.php:108
Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(418): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#1 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(106): with()
#2 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecation()
#3 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#4 /app/vendor/anourvalar/eloquent-serialize/src/Grammars/EloquentBuilderGrammar.php(108): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#5 /app/vendor/anourvalar/eloquent-serialize/src/Grammars/EloquentBuilderGrammar.php(64): AnourValar\EloquentSerialize\Service->cleanStaticConstraints()
#6 /app/vendor/anourvalar/eloquent-serialize/src/Grammars/EloquentBuilderGrammar.php(16): AnourValar\EloquentSerialize\Service->getEagers()
#7 /app/vendor/anourvalar/eloquent-serialize/src/Grammars/ModelGrammar.php(18): AnourValar\EloquentSerialize\Service->packEloquentBuilder()
#8 /app/vendor/anourvalar/eloquent-serialize/src/Service.php(19): AnourValar\EloquentSerialize\Service->pack()
#9 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): AnourValar\EloquentSerialize\Service->serialize()
```

To give some context, here are the variables from the debugger:
```
$item = false
$key = {int} 0
$packedQueryBuilder = {array} [16]
 bindings = {array} [9]
  select = {array} [0]
  from = {array} [0]
  join = {array} [0]
  where = {array} [0]
  groupBy = {array} [0]
  having = {array} [0]
  order = {array} [0]
  union = {array} [0]
  unionOrder = {array} [0]
 aggregate = null
 columns = null
 distinct = false
 from = "subscription_items"
 wheres = {array} [0]
 groups = null
 havings = null
 orders = null
 limit = null
 offset = null
 unions = null
 unionLimit = null
 unionOffset = null
 unionOrders = null
 joins = null
$packedReferenceQueryBuilder = {array} [16]
 bindings = {array} [9]
  select = {array} [0]
  from = {array} [0]
  join = {array} [0]
  where = {array} [0]
  groupBy = {array} [0]
  having = {array} [0]
  order = {array} [0]
  union = {array} [0]
  unionOrder = {array} [0]
 aggregate = null
 columns = null
 distinct = false
 from = "subscription_items"
 wheres = {array} [0]
 groups = null
 havings = null
 orders = null
 limit = null
 offset = null
 unions = null
 unionLimit = null
 unionOffset = null
 unionOrders = null
 joins = null
$properties = {array} [14]
 0 = "aggregate"
 1 = "columns"
 2 = "distinct"
 3 = "wheres"
 4 = "groups"
 5 = "havings"
 6 = "orders"
 7 = "limit"
 8 = "offset"
 9 = "unions"
 10 = "unionLimit"
 11 = "unionOffset"
 12 = "unionOrders"
 13 = "joins"
$property = "distinct"
$this = {AnourValar\EloquentSerialize\Service} [0]
$_ENV = {array} [37]
$_SERVER = {array} [41]
```

**Comment by AnourValar** [comment]
Hello! I've made some changes for supporting PHP 8.1 with E_DEPRECATION turned on.
New version is already available. Thanks one more time :)

**Comment by oprypkhantc** [comment]
Thanks :)
